---
abstract: 'Check spelling in Padre, The Perl IDE.'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Padre::Plugin::SpellCheck
name: Padre-Plugin-SpellCheck
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Class::Accessor: 0.34
  File::Which: 1.09
  Moo: 1.000007
  Padre: 0.96
  Text::Hunspell: 2.05
  Try::Tiny: 0.12
  perl: 5.10.1
resources:
  bugtracker: http://padre.perlide.org/trac
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginSpellCheck
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-SpellCheck/
version: 1.31_03
