---
abstract: 'Check spelling in Padre The Perl IDE'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Padre::Plugin::SpellCheck
name: Padre-Plugin-SpellCheck
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Class::XSAccessor: 1.13
  File::Which: 1.09
  Module::Util: 1.07
  Padre: 0.93
  perl: 5.8.5
resources:
  bugtracker: http://padre.perlide.org/trac
  homepage: http://padre.perlide.org/trac/wiki/PadrePluginSpellCheck
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-SpellCheck/
version: 1.23
